Begin the readme with the quick start
gvolpe/sbt-nix.g8 pull request #4
Opened 2020-10-21 15:50 UTC by kubukoz

I think many people might be discouraged when they see a long document with all the motivation, the about section etc. - putting the instructions to "just start" in the beginning might be a good idea.

2020-10-21 17:00 UTC, gvolpe requested changes

2020-10-21 17:00 UTC, gvolpe commented on README.md
> +New Scala projects using `sbt` are usually created using `g8` templates by running `sbt new template.g8`. However, a bit earlier it was recommended to not install `sbt` globally. So, if that's the ca
I think it's a good idea but we would need to rephrase this "a bit earlier" comment and I don't want that because there's an entire reason previously explained why we don't have `sbt` and `java` installed globally.

However, I think we could add another small section at the top named "Quick start" or something that shows how to get started with the opinionated template but that we encourage users to read the guide step by step.

2020-10-21 18:31 UTC, kubukoz commented on README.md
> +New Scala projects using `sbt` are usually created using `g8` templates by running `sbt new template.g8`. However, a bit earlier it was recommended to not install `sbt` globally. So, if that's the ca
Hah, yeah, I just moved this block without thinking too much about it. Maybe just a a single snippet prefixed with "if you're familiar with X, Y and Z, you can just run this:"?

and just `nix-shell -p sbt --run "sbt new gvolpe/sbt-nix.g8"` in the snippet.

2020-10-21 19:44 UTC, gvolpe commented on README.md
> +New Scala projects using `sbt` are usually created using `g8` templates by running `sbt new template.g8`. However, a bit earlier it was recommended to not install `sbt` globally. So, if that's the ca
Yeah something like that could work :+1:

2020-12-21 09:50 UTC, gvolpe commented on README.md
> +New Scala projects using `sbt` are usually created using `g8` templates by running `sbt new template.g8`. However, a bit earlier it was recommended to not install `sbt` globally. So, if that's the ca
Hey yo! :nerd_face:

2021-01-06 14:12 UTC, kubukoz commented on README.md
> +New Scala projects using `sbt` are usually created using `g8` templates by running `sbt new template.g8`. However, a bit earlier it was recommended to not install `sbt` globally. So, if that's the ca
looking at this again :P damn, it's been 3 months since the talk 😅

2021-01-06 15:24 UTC, kubukoz commented
That should do the trick @gvolpe :)

2021-01-06 15:45 UTC, gvolpe approved these changes
Thanks!

2021-01-06 15:45 UTC, merged